services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    depends_on:
      - postgres # Wait for postgress

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - api # Wait for api
